Feature/bridge native erc677 - PART ONE (FOREIGN TO HOME)
xdaichain/omnibridge pull request #208
Opened 2021-04-11 14:23 UTC by sunguru98

I have basically planned to cover up this issue in 2 parts. Foreign to home (this one), and view versa. 

The plan was to keep the native currency option at the top for easy access, followed by the tokens. 
<img width="476" alt="Screenshot 2021-04-11 at 7 51 20 PM" src="https://user-images.githubusercontent.com/32637757/114307884-4cc13300-9aff-11eb-9ca3-d4185af96b9a.png">

I have attached the transaction as well as some screenshots beneath for the demo transfer which was done from the native currency of KOVAN (KETH) to SOKOL (WKETH), 

Transaction Hash - https://kovan.etherscan.io/tx/0xafe6c3dc0e89effaf6eff1e1aba5a94c5b238ec72c3b0f3d0c6d8abc76997c6e

Execution completion -
![](https://cdn.discordapp.com/attachments/819639802231259136/830797555171590144/Screenshot_2021-04-11_at_7.02.43_PM.png)

AMB Confirmation -
<img width="1275" alt="Screenshot 2021-04-11 at 7 53 11 PM" src="https://user-images.githubusercontent.com/32637757/114307931-8e51de00-9aff-11eb-9d4a-9a4ba5fef025.png">

2021-04-12 08:39 UTC, dan13ram commented on packages/react-app/src/components/modals/TokenSelectorModal.jsx
> +          balance: NATIVE_CURRENCY_SYBMOLS.includes(token.symbol)
Dont do this. There might be a token with the same symbol. Instead do a mode match maybe or an address === ADRESS_ZERO match.

2021-04-12 08:44 UTC, dan13ram commented on packages/react-app/src/lib/bridge.js
> +  if (NATIVE_CURRENCY_SYBMOLS.includes(fromSybmol)) {
There might be token BNB on mainnet or ETH or BSC or something else like that. Should do this in a cleaner manner.

2021-04-12 08:46 UTC, dan13ram commented on packages/react-app/src/lib/bridge.js
> +      { name: `W${fromSybmol}` },
```suggestion
```
Don't give this input and it will fetch it automatically.

2021-04-12 08:48 UTC, dan13ram commented on packages/react-app/src/lib/bridge.js
> +export const wrapAndRelayTokens = async (
I think it would make more sense to move this to the same method above? and do a switch case for mode === "NATIVE" ?

2021-04-12 08:50 UTC, dan13ram commented on packages/react-app/src/contexts/BridgeContext.jsx
> +      const tx = NATIVE_CURRENCY_SYBMOLS.includes(fromToken.symbol)
the symbol check as mentioned in other places should not used. Use either `mode === NATIVE` check or some other custom param.
Also here that mode check can be done inside `relayTokens` itself, removing the logic from this method and taking it deeper inside.

2021-04-12 08:52 UTC, dan13ram commented on packages/react-app/src/lib/constants.js
> +export const NATIVE_CURRENCY_SYBMOLS = ['ETH', 'KETH', 'BNB'];
SYMBOLS misspelled as SYBMOLS.

2021-04-12 08:53 UTC, dan13ram commented on packages/react-app/src/lib/constants.js
> +export const nativeCurrencyMediators = {
Call this Helper to keep the naming scheme same everywhere.

2021-04-12 08:55 UTC, dan13ram commented on packages/react-app/src/lib/token.js
> +  if (NATIVE_CURRENCY_SYBMOLS.includes(token.symbol)) {
Again no symbol check. Maybe set the mode in `constants` file itself and use that here. Or we could also skip this call to fetchTokenDetails for NATIVE tokens cause all info is already known.

2021-04-12 08:55 UTC, dan13ram commented on packages/react-app/src/lib/token.js
> +  if (NATIVE_CURRENCY_SYBMOLS.includes(symbol)) {
No symbol check.

2021-04-12 08:56 UTC, dan13ram commented on packages/react-app/src/components/modals/TokenSelectorModal.jsx
> +      const natCurIndex = tokenListWithBalance.findIndex(({ symbol }) =>
Should not do a symbol check to find the token.

2021-04-12 08:58 UTC, dan13ram requested changes
Requested a few changes. Mainly need to get rid of symbol check to ascertain if the token is the Native token, since there could be multiple tokens with the same symbol.

2021-04-12 09:01 UTC, dan13ram commented on packages/react-app/src/lib/constants.js
> +export const NATIVE_CURRENCY_CHAIN_IDS = [1, 42, 56];
Could we remove these constants and have these symbols or if native currency is enabled as part of the `lib/networks` file? 
Also need to disable showing `ETH` (native currency) for mainnet until the helper contracts are reviewed and deployed.

2021-04-12 19:31 UTC, sunguru98 commented
These changes would be made over the sub branch (feature/bridge-native-erc677-home), as it would be easy for you @dan13ram

2021-04-13 10:27 UTC, dan13ram commented
Closing this in favor of #209

2021-04-13 10:27 UTC, closed without merging